// Code generated by MockGen. DO NOT EDIT.
// Source: ./common/pdfgenerator/init.go

// Package mock_pdfgenerator is a generated GoMock package.
package mock_pdfgenerator

import (
	reflect "reflect"

	pdfgenerator "github.com/GregChrisnaDev/Amartha-Sol-3/common/pdfgenerator"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GenerateAgreementLetter mocks base method.
func (m *MockClient) GenerateAgreementLetter(data pdfgenerator.AgreementLetterPDF) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAgreementLetter", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAgreementLetter indicates an expected call of GenerateAgreementLetter.
func (mr *MockClientMockRecorder) GenerateAgreementLetter(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAgreementLetter", reflect.TypeOf((*MockClient)(nil).GenerateAgreementLetter), data)
}
